function skillsMember() {
    return {
        title: "Skills",
        skills: [
            "HTML",
            "CSS",
            "JavaScript",
            "React",
            "Node.js",
            "Express",
            "MongoDB",
            "Python",
            "Django",
            "Flask",
            "C++",
            "C#",
            "Java",
            "PHP",
            "Laravel",
            "Vue.js",
            "Angular",
            "Bootstrap",
            "Tailwind CSS",
            "SASS",
            "Git",
            "GitHub",
            "Docker",
            "Kubernetes",
            "Jenkins",
            "AWS",
            "Azure",
            "Google Cloud",
            "Heroku",
            "Netlify",
            "Firebase",
            "GraphQL",
            "REST API",
            "SQL",
            "NoSQL",
            "Agile",
            "Scrum",
            "Kanban",
            "Trello",
            "Jira",
            "Figma",
            "Adobe XD",
            "Photoshop",
            "Illustrator",
            "After Effects",
            "Premiere Pro",
            "Final Cut Pro",
            "Blender",
            "Unity",
            "Unreal Engine",
            "3DS Max",
            "Maya",
            "ZBrush",
            "AutoCAD",
            "SolidWorks",
        ],
    };
}